// A curated list of common English words for editor autocomplete (Tier B).
// Native browser spellcheck handles corrections; this provides type-ahead suggestions.
// Kept compact on purpose; extend freely or swap for a fuller dictionary later.

export const COMMON_WORDS: string[] = [
  "about", "above", "accept", "access", "according", "account", "accurate", "achieve",
  "acquire", "across", "action", "active", "activity", "actually", "additional", "address",
  "administration", "advantage", "agreement", "algorithm", "allow", "almost", "already",
  "alternative", "although", "always", "analysis", "analytics", "another", "answer", "anything",
  "application", "apply", "approach", "appropriate", "architecture", "around", "associated",
  "attention", "authentication", "available", "average", "because", "become", "before", "behavior",
  "behind", "believe", "benefit", "better", "between", "beyond", "business", "calculate", "cannot",
  "capability", "capacity", "category", "certain", "challenge", "change", "channel", "chapter",
  "citation", "classification", "client", "cloud", "collaboration", "collection", "command",
  "comment", "common", "communication", "community", "company", "compare", "complete", "complex",
  "compliance", "component", "comprehensive", "compute", "concept", "condition", "confidence",
  "configuration", "connect", "connection", "consider", "consistent", "container", "content",
  "context", "continue", "contract", "control", "conversation", "corporate", "correct", "create",
  "critical", "current", "customer", "dashboard", "database", "decision", "decrease", "default",
  "define", "delivery", "department", "deploy", "deployment", "describe", "description", "design",
  "detail", "detect", "detection", "determine", "develop", "development", "different", "difficult",
  "directly", "document", "documentation", "during", "dynamic", "effective", "efficient", "either",
  "element", "embedding", "employee", "enable", "encryption", "engineer", "engineering", "enough",
  "enterprise", "entire", "entity", "environment", "especially", "establish", "evaluate",
  "evaluation", "even", "event", "every", "evidence", "example", "execute", "experience",
  "explain", "extract", "feature", "figure", "filter", "financial", "follow", "format",
  "framework", "function", "further", "general", "generate", "generation", "graph", "ground",
  "hallucination", "handle", "happen", "headquarters", "however", "human", "ideal", "identify",
  "important", "improve", "include", "increase", "index", "indicate", "individual", "industry",
  "information", "infrastructure", "ingestion", "initial", "instance", "instead", "integration",
  "intelligence", "interface", "internal", "introduce", "issue", "knowledge", "language", "large",
  "latency", "layer", "leadership", "learning", "level", "leverage", "limited", "listen", "machine",
  "maintain", "manage", "management", "many", "market", "material", "matter", "maximum", "measure",
  "mechanism", "memory", "message", "method", "metric", "minimum", "model", "moment", "monitor",
  "multiple", "natural", "nearly", "necessary", "network", "neural", "obtain", "official", "operate",
  "operation", "opportunity", "option", "organization", "original", "output", "package", "paragraph",
  "parameter", "particular", "pattern", "perform", "performance", "perhaps", "permission", "pipeline",
  "platform", "policy", "position", "possible", "potential", "practice", "precision", "predict",
  "prepare", "present", "prevent", "previous", "primary", "principle", "private", "probably",
  "problem", "process", "produce", "product", "production", "professional", "program", "project",
  "property", "protect", "protocol", "provide", "purpose", "quality", "query", "question", "quickly",
  "rather", "reason", "receive", "recent", "recognize", "recommend", "record", "reduce", "reference",
  "region", "relate", "relationship", "release", "relevant", "reliable", "remain", "remember",
  "remove", "report", "represent", "request", "require", "requirement", "research", "resource",
  "response", "result", "retrieval", "return", "review", "scalable", "schedule", "science", "search",
  "second", "section", "security", "sentence", "separate", "sequence", "server", "service", "session",
  "several", "should", "signal", "similar", "simple", "single", "software", "solution", "source",
  "specific", "standard", "statement", "storage", "strategy", "stream", "structure", "subject",
  "success", "suggest", "summary", "support", "system", "table", "target", "technical", "technology",
  "template", "testing", "though", "thought", "through", "together", "token", "toward", "training",
  "transfer", "transform", "trigger", "understand", "uploaded", "usually", "validate", "value",
  "variable", "vector", "verify", "version", "viewer", "warning", "whether", "within", "without",
  "workspace", "writing",
];
